export const Slangs = [
    { id: 1, slang: "How far?", meaning: "How are you?"},
    { id: 2, slang: "Japa", meaning: "To run away or escape"},
    { id: 3, slang: "E choke", meaning: "That's impressive!" },
    { id: 4, slang: "Kpele", meaning: "Sorry or take heart" },
    { id: 5, slang: "Abi?", meaning: "Right? Isn't it?" },
    { id: 6, slang: "How you dey?", meaning: "How are you?"},
    { id: 7, slang: "You too much", meaning: "You are far too kind." },
    { id: 8, slang: "I wan Chop / I dey H", meaning: "I want to eat" },
    { id: 9, slang: "K-leg", meaning: "The situation or topic is either suspicious or untrue." },
    { id: 10, slang: "E be like film", meaning: "This phrase is used to express incredulity, especially when reporting a scenario, movie or circumstance." },
    { id: 11, slang: "Na so/Na so?", meaning: "This means 'It is so' or 'I concur/ is that so?" },
    { id: 12, slang: "Notin Spoil", meaning: "This means all is well." },
    { id: 13, slang: "Gbam!", meaning: "This is a response that means exactly or precisely." },
    { id: 14, slang: "Abeg", meaning: "This simply means 'Please.' " },
    { id: 15, slang: "I no get", meaning: "I dont have it" },
    { id: 16, slang: "Go Slow", meaning: "This means 'Traffic Jam.’ " },
    { id: 17, slang: "Comot", meaning: "This could mean 'go', 'leave', or 'get out!'" },
    { id: 18, slang: "Dey", meaning: "This is the pidgin form of the verb 'to be'." },
    { id: 19, slang: "Wetin?", meaning: "This means 'What?'" },
    { id: 20, slang: "I Sabi", meaning: "'I know', or 'I understand.'" },
    { id: 21, slang: "Wahala", meaning: "This means 'Trouble'" },
    { id: 22, slang: "God don butter my bread", meaning: "God has answered my prayers." },
    { id: 23, slang: "Kpatakpata", meaning: "Completely / Totally" },
    { id: 24, slang: "Kpatakpata of them all", meaning: "The ultimate" },
    { id: 25, slang: "Pikin", meaning: "Child" },
    { id: 26, slang: "Carry go", meaning: "Move on / Proceed" },
    { id: 27, slang: "Waka", meaning: "This means 'Walk / Go" },
    { id: 28, slang: "Yarn", meaning: "Speak / Talk" },
    { id: 29, slang: "Gbege", meaning: "Trouble / Problem" },
    { id: 30, slang: "No vex", meaning: "Don’t be angry" },
    { id: 31, slang: "Dash", meaning: "Give for free" },
    { id: 32, slang: "Sharp-sharp", meaning: "Quickly" },
    { id: 33, slang: "Area boy", meaning: "Street thug / Gang member" },
    { id: 34, slang: "Palava", meaning: "Problem / Trouble" },
    { id: 35, slang: "Ajebutter", meaning: "Privileged child / Rich kid" },
    { id: 36, slang: "Ajepako", meaning: "Less privileged child" },
    { id: 37, slang: "Ehen", meaning: "Okay / So / I see" },
    { id: 38, slang: "Kolo", meaning: "Go crazy / Act foolishly" },
    { id: 39, slang: "Naija", meaning: "Nigeria" },
    { id: 40, slang: "Belle", meaning: "Stomach" },
    { id: 41, slang: "Katakata", meaning: "Chaos / Trouble" },
    { id: 42, slang: "Aboki", meaning: "Friend (often used for Northerners)" },
    { id: 43, slang: "As e dey hot", meaning: "Immediately / Quickly" },
    { id: 44, slang: "Tuale", meaning: "Salute / Respect" },
    { id: 45, slang: "Kukuma", meaning: "Might as well / Simply" },
    { id: 46, slang: "Fashi", meaning: "Forget about it / Leave it" },
    { id: 47, slang: "Oyinbo", meaning: "White person / Foreigner" },
    { id: 48, slang: "Shebi", meaning: "Isn’t it? / Right?" },
    { id: 49, slang: "Para", meaning: "Get angry / Overreact" },
    { id: 50, slang: "E don tey", meaning: "It’s been a long time" },
    { id: 51, slang: "Mama", meaning: "Mother" },
    { id: 52, slang: "Papa", meaning: "Father" },
    { id: 53, slang: "Shishi", meaning: "No money / Nothing at all" },
    { id: 54, slang: "Wetin dey sup?", meaning: "What’s happening? / What’s up?" },
    { id: 55, slang: "E don red", meaning: "Things are tough / It’s a critical situation" },
    { id: 56, slang: "Ginger", meaning: "Motivation / Energy" },
    { id: 57, slang: "Kpai", meaning: "Die / Finish completely" },
    { id: 58, slang: "Zobo", meaning: "Lies / Falsehood" },
    { id: 59, slang: "Okada", meaning: "Motorcycle (commercial bike)" },
    { id: 60, slang: "E go beta", meaning: "It will be better" },
    { id: 61, slang: "Fire down ", meaning: "Continue / Go ahead" },
    { id: 62, slang: "E no concern me", meaning: "It’s none of my business" },
    { id: 63, slang: "Hammer", meaning: "Hit the jackpot / Make a lot of money" },
    { id: 64, slang: "Run things", meaning: "To handle things / Make things happen" },
    { id: 65, slang: "Ogbonge", meaning: "Authentic / Top-notch" },
    { id: 66, slang: "Apollo", meaning: "Conjunctivitis" },
    { id: 67, slang: "Gbese", meaning: "Debt / Trouble" },
    { id: 68, slang: "Soft work", meaning: "Easy task / Job well done" },
    { id: 69, slang: "Na you sabi", meaning: "That’s your business / It’s up to you" },
    { id: 70, slang: "Dey there dey play", meaning: "Stop wasting time / Be serious" },
    { id: 71, slang: "On top wetin?", meaning: "For what reason? / Why?" },
    { id: 72, slang: "Maga", meaning: "Gullible person (often used for scam victims)" },
    { id: 73, slang: "E be tins", meaning: "That’s how it is / It’s just life" },
    { id: 74, slang: "Form", meaning: "To pretend / Act cool" },
    { id: 75, slang: "You don baff?", meaning: "Have you taken a bath?" },
    { id: 76, slang: "Shine your eye", meaning: "Be alert / Be careful" },
    { id: 77, slang: "Gbe body", meaning: "Move your body (often in dancing)" },
    { id: 78, slang: "Jaiye", meaning: "Enjoy life" },
    { id: 79, slang: "Na who sabi?", meaning: "Who knows?" },
    { id: 80, slang: "Flex", meaning: "To enjoy / Show off" },
    { id: 81, slang: "My guy", meaning: "My friend" },
    { id: 82, slang: "Olodo", meaning: "A dull person / Someone foolish" },
    { id: 83, slang: "Street", meaning: "The hustle / The grind" },
    { id: 84, slang: "Tory", meaning: "Story / News" },
    { id: 85, slang: "Abeg shift", meaning: "Please move aside" },
    { id: 86, slang: "Body dey pepper me ", meaning: "I’m feeling excited or restless" },
    { id: 87, slang: "Beta pikin", meaning: "Good child" },
    { id: 88, slang: "Catch cruise", meaning: "Have fun / Enjoy the moment" },
    { id: 89, slang: "Shey you dey whine me?", meaning: "Are you joking with me?" },
    { id: 90, slang: "Tear eye", meaning: "To become aware / Wisen up" },
    { id: 91, slang: "I no send", meaning: "I don’t care" },
    { id: 92, slang: "Chook mouth ", meaning: "Interfere / Join a conversation" },
    { id: 93, slang: "Yawa", meaning: "Trouble / Problem" },
    { id: 94, slang: "Carry last ", meaning: "To fail / Be left behind" },
    { id: 95, slang: "Aluta", meaning: "Struggle (often used for student activism)" },
    { id: 96, slang: "Chop knuckle", meaning: "Give a fist bump / Well done" },
    { id: 97, slang: "You no try", meaning: "You didn’t do well / That’s unfair" },
    { id: 98, slang: "Hold body ", meaning: "Be patient / Stay calm" },
    { id: 99, slang: "E no pure", meaning: "It’s suspicious / Doesn’t seem right" },
    { id: 100, slang: "Press am", meaning: "Push harder / Keep going" },
    { id: 101, slang: "I go show you", meaning: "I’ll prove it to you." },
    { id: 102, slang: "Over sabi ", meaning: "Someone who knows too much or acts like they do." },
    { id: 103, slang: "Gree", meaning: "Agree" },
    { id: 104, slang: "No mind am", meaning: "Don’t mind him/her." },
    { id: 105, slang: "Nack am", meaning: "Hit it/give it (literal or figurative)." },
    { id: 106, slang: "E sure for me ", meaning: "I am confident about it." },
    { id: 107, slang: "How you see am?", meaning: "What do you think about it?" },
    { id: 108, slang: "No be today ", meaning: "This has been happening for a long time." },
    { id: 109, slang: "Fire for fire", meaning: "Retaliation or matching energy." },
    { id: 110, slang: "I don jam am", meaning: "I’ve met or encountered it." },
    { id: 111, slang: "Beta soup na money kill am", meaning: "Good things cost money." },
    { id: 112, slang: "Hold your side", meaning: "Mind your business." },
    { id: 113, slang: "You do well ", meaning: "Thank you / You did well." },
    { id: 114, slang: "Na you biko ", meaning: "You’re the one, please." },
    { id: 115, slang: "As I dey like this", meaning: "In my current situation." },
    { id: 116, slang: "Fall my hand", meaning: "Disappoint me." },
    { id: 117, slang: "Omo see levels", meaning: "Wow, look at the upgrade!" },
    { id: 118, slang: "Arrange your sef ", meaning: "Get yourself together." },
    { id: 119, slang: "I go reason am", meaning: "I’ll think about it." },
    { id: 120, slang: "Yawa don gas", meaning: "Trouble has started." },
    { id: 121, slang: "Omo dem plenty", meaning: "There are so many of them." },
    { id: 122, slang: "Calm down", meaning: "Relax / Be patient." },
    { id: 123, slang: "E no follow ", meaning: "It doesn’t count / It’s irrelevant." },
    { id: 124, slang: "Scatter ground ", meaning: "Make a big impact." },
    { id: 125, slang: "No be beans ", meaning: "t’s not easy." },
    { id: 126, slang: "Sharp guy", meaning: "Smart or streetwise person." },
    { id: 127, slang: "Do anyhow, you go see anyhow ", meaning: "Your actions will have consequences." },
    { id: 128, slang: "This one na confirm ", meaning: "This is authentic." },
    { id: 129, slang: "Softly softly ", meaning: "Take it easy." },
    { id: 130, slang: "Baff up ", meaning: "Dress nicely." },
    { id: 131, slang: "E sweet my belle", meaning: "It makes me happy." },
    { id: 132, slang: "Hala me", meaning: "Call or contact me." },
    { id: 133, slang: "No dull", meaning: "Don’t waste time or slack." },
    { id: 136, slang: "No carry me go where I no know", meaning: "Don’t confuse me." },
    { id: 140, slang: "Na lie!", meaning: " That’s not true! / You’re joking!" },
    { id: 141, slang: "Shakara", meaning: "Show-off or prideful behavior." },
    { id: 142, slang: "Abeg free me", meaning: "Please leave me alone." },
    { id: 143, slang: "Omo I don tire", meaning: "I’m exhausted." },
    { id: 144, slang: "You no fit try am", meaning: "You can’t attempt it." },
    { id: 145, slang: "Chop my eye", meaning: "Deceive me or lie to me." },
    { id: 146, slang: "Na today? ", meaning: " Is this new? / This has been happening." },
    { id: 147, slang: "Dem don cast", meaning: "They’ve been exposed." },
    { id: 148, slang: "Chook hand", meaning: "Put your hand in (literally or figuratively)." },
    { id: 149, slang: "Borrow pose", meaning: "Fake confidence or act important." },
    { id: 150, slang: "Agbada", meaning: "Large traditional garment usually worn by men over a shirt." },
    { id: 151, slang: "Bobbi", meaning: "Breast." },
    { id: 152, slang: "Mamaput", meaning: "Roadside restaurant." },
    { id: 153, slang: "Butta my bread", meaning: "Answered prayer." },
    { id: 154, slang: "Dada", meaning: "Dread locks." },
    { id: 155, slang: "Gallop", meaning: "Pot holes in road." },
    { id: 156, slang: "Awoof", meaning: "Freebie. Without charge." },
    { id: 157, slang: "Yab", meaning: "Abuse or make fun of." },
    { id: 158, slang: "Yafu yafu", meaning: "Plenty" },
    { id: 159, slang: "Winch", meaning: "Witch." },
    { id: 160, slang: "Throway salute", meaning: "Big shout out to." },
    { id: 160, slang: "Throway face", meaning: "Avoid eye contact or snub" },





  ];

