export const Slangs = [
    { id: 1, slang: "How far?", meaning: "How are you?"},
    { id: 2, slang: "Japa", meaning: "To run away or escape"},
    { id: 3, slang: "E choke", meaning: "That's impressive!" },
    { id: 4, slang: "Kpele", meaning: "Sorry or take heart" },
    { id: 5, slang: "Abi?", meaning: "Right? Isn't it?" },
    { id: 6, slang: "How you dey?", meaning: "How are you?"},
    { id: 7, slang: "You too much", meaning: "You are far too kind." },
    { id: 8, slang: "I wan Chop / I dey H", meaning: "I want to eat" },
    { id: 9, slang: "K-leg", meaning: "The situation or topic is either suspicious or untrue." },
    { id: 10, slang: "E be like film", meaning: "This phrase is used to express incredulity, especially when reporting a scenario, movie or circumstance." },
    { id: 11, slang: "Na so/Na so?", meaning: "This means 'It is so' or 'I concur/ is that so?" },
    { id: 12, slang: "Notin Spoil", meaning: "This means all is well." },
    { id: 13, slang: "Gbam!", meaning: "This is a response that means exactly or precisely." },
    { id: 14, slang: "Abeg", meaning: "This simply means 'Please.' " },
    { id: 15, slang: "I no get", meaning: "I dont have it" },
    { id: 16, slang: "Go Slow", meaning: "This means 'Traffic Jam.’ " },
    { id: 17, slang: "Comot", meaning: "This could mean 'go', 'leave', or 'get out!'" },
    { id: 18, slang: "Dey", meaning: "This is the pidgin form of the verb 'to be'." },
    { id: 19, slang: "Wetin?", meaning: "This means 'What?'" },
    { id: 20, slang: "I Sabi", meaning: "'I know', or 'I understand.'" },
    { id: 21, slang: "Wahala", meaning: "This means 'Trouble'" },
    { id: 22, slang: "God don butter my bread", meaning: "God has answered my prayers." },
    { id: 23, slang: "Kpatakpata", meaning: "Completely / Totally" },
    { id: 24, slang: "Shakara", meaning: "Show off / Boast" },
    { id: 25, slang: "Pikin", meaning: "Child" },
    { id: 26, slang: "Carry go", meaning: "Move on / Proceed" },
    { id: 27, slang: "Waka", meaning: "This means 'Walk / Go" },
    { id: 28, slang: "Yarn", meaning: "Speak / Talk" },
    { id: 29, slang: "Gbege", meaning: "Trouble / Problem" },
    { id: 30, slang: "No vex", meaning: "Don’t be angry" },
    { id: 31, slang: "Dash", meaning: "Give for free" },
    { id: 32, slang: "Sharp-sharp", meaning: "Quickly" },
    { id: 33, slang: "Area boy", meaning: "Street thug / Gang member" },
    { id: 34, slang: "Palava", meaning: "Problem / Trouble" },
    { id: 35, slang: "Ajebutter", meaning: "Privileged child / Rich kid" },
    { id: 36, slang: "Ajepako", meaning: "Less privileged child" },
    { id: 37, slang: "Ehen", meaning: "Okay / So / I see" },
    { id: 38, slang: "Kolo", meaning: "Go crazy / Act foolishly" },
    { id: 39, slang: "Naija", meaning: "Nigeria" },
    { id: 40, slang: "Belle", meaning: "Stomach" },
    { id: 41, slang: "Katakata", meaning: "Chaos / Trouble" },
    { id: 42, slang: "Aboki", meaning: "Friend (often used for Northerners)" },
    { id: 43, slang: "As e dey hot", meaning: "Immediately / Quickly" },
    { id: 44, slang: "Tuale", meaning: "Salute / Respect" },
    { id: 45, slang: "Kukuma", meaning: "Might as well / Simply" },
    { id: 46, slang: "Fashi", meaning: "Forget about it / Leave it" },
    { id: 47, slang: "Oyinbo", meaning: "White person / Foreigner" },
    { id: 48, slang: "Shebi", meaning: "Isn’t it? / Right?" },
    { id: 49, slang: "Para", meaning: "Get angry / Overreact" },
    { id: 50, slang: "E don tey", meaning: "It’s been a long time" },
    { id: 51, slang: "Mama", meaning: "Mother" },
    { id: 52, slang: "Papa", meaning: "Father" },
    { id: 53, slang: "Shishi", meaning: "No money / Nothing at all" },
    { id: 54, slang: "Wetin dey sup?", meaning: "What’s happening? / What’s up?" },
    { id: 55, slang: "E don red", meaning: "Things are tough / It’s a critical situation" },
    { id: 56, slang: "Ginger", meaning: "Motivation / Energy" },
    { id: 57, slang: "Kpai", meaning: "Die / Finish completely" },
    { id: 58, slang: "Zobo", meaning: "Lies / Falsehood" },
    { id: 59, slang: "Okada", meaning: "Motorcycle (commercial bike)" },
    { id: 60, slang: "E go beta", meaning: "It will be better" },
    { id: 61, slang: "Fire down ", meaning: "Continue / Go ahead" },
    { id: 62, slang: "E no concern me", meaning: "It’s none of my business" },
    { id: 63, slang: "Hammer", meaning: "Hit the jackpot / Make a lot of money" },
    { id: 64, slang: "Run things", meaning: "To handle things / Make things happen" },
    { id: 65, slang: "Ogbonge", meaning: "Authentic / Top-notch" },
    { id: 66, slang: "Kpatakpata of them all", meaning: "The ultimate" },
    { id: 67, slang: "Gbese", meaning: "Debt / Trouble" },
    { id: 68, slang: "Soft work", meaning: "Easy task / Job well done" },
    { id: 69, slang: "Na you sabi", meaning: "That’s your business / It’s up to you" },
    { id: 70, slang: "Dey there dey play", meaning: "Stop wasting time / Be serious" },
    { id: 71, slang: "On top wetin?", meaning: "For what reason? / Why?" },
    { id: 72, slang: "Maga", meaning: "Gullible person (often used for scam victims)" },
    { id: 73, slang: "E be tins", meaning: "That’s how it is / It’s just life" },
    { id: 74, slang: "Form", meaning: "To pretend / Act cool" },
    { id: 75, slang: "You don baff?", meaning: "Have you taken a bath?" },
    { id: 76, slang: "Shine your eye", meaning: "Be alert / Be careful" },
    { id: 77, slang: "Gbe body", meaning: "Move your body (often in dancing)" },
    { id: 78, slang: "Jaiye", meaning: "Enjoy life" },
    { id: 79, slang: "Na who sabi?", meaning: "Who knows?" },
    { id: 80, slang: "Flex", meaning: "To enjoy / Show off" },
    { id: 81, slang: "My guy", meaning: "My friend" },
    { id: 82, slang: "Olodo", meaning: "A dull person / Someone foolish" },
    { id: 83, slang: "Street", meaning: "The hustle / The grind" },
    { id: 84, slang: "Tory", meaning: "Story / News" },
    { id: 85, slang: "Abeg shift", meaning: "Please move aside" },
    { id: 86, slang: "Body dey pepper me ", meaning: "I’m feeling excited or restless" },
    { id: 87, slang: "Beta pikin", meaning: "Good child" },
    { id: 88, slang: "Catch cruise", meaning: "Have fun / Enjoy the moment" },
    { id: 89, slang: "Shey you dey whine me?", meaning: "Are you joking with me?" },
    { id: 90, slang: "Tear eye", meaning: "To become aware / Wisen up" },
    { id: 91, slang: "I no send", meaning: "I don’t care" },
    { id: 92, slang: "Chook mouth ", meaning: "Interfere / Join a conversation" },
    { id: 93, slang: "Yawa", meaning: "Trouble / Problem" },
    { id: 94, slang: "Carry last ", meaning: "To fail / Be left behind" },
    { id: 95, slang: "Aluta", meaning: "Struggle (often used for student activism)" },
    { id: 96, slang: "Chop knuckle", meaning: "Give a fist bump / Well done" },
    { id: 97, slang: "You no try", meaning: "You didn’t do well / That’s unfair" },
    { id: 98, slang: "Hold body ", meaning: "Be patient / Stay calm" },
    { id: 99, slang: "E no pure", meaning: "It’s suspicious / Doesn’t seem right" },
    { id: 100, slang: "Press am", meaning: "Push harder / Keep going" }




  ];

